spring:
  application:
    name: todo-social-app

  datasource:
    url: jdbc:mysql://localhost:3306/todosocialappdb
    username: todoapp
    password: socialapp
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"